spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8089/
          predicates:
            - Path=/api/customers/**
        - id : r2
          uri: http://localhost:8088/
          predicates:
            - Path=/orders/**
        - id : r3
          uri: http://localhost:8087/
          predicates:
            - Path=/api/products/**
  application:
    name: gateway-service
server:
  port: 8888